### ISSUE TITLE
Python 2 compatibility

### ISSUE THREAD

**Issue by GreenRiverRUS** [legnaleurc/wcpan.telegram#5]
If you aren't going to support python2, this line
https://github.com/legnaleurc/wcpan.telegram/blob/master/wcpan/telegram/util.py#L61
can be rewritten using dict comprehention, and become more readable in my opinion.

**Comment by legnaleurc** [comment]
Yes I don't care Python 2 at all.
I'll do that if I have enough bandwidth.
